import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import Editor from '@monaco-editor/react';
import { connectionsApi } from '../api/connections.api';
import { queryApi } from '../api/query.api';
import { useSchemaExtract } from '../hooks/useSchemaExtract';
import { useWorkspaceStore } from '../store/workspaceStore';
import {
  Play,
  Loader2,
  Database,
  CheckCircle2,
  Table as TableIcon,
  ShieldAlert,
  ArrowRight,
  Sparkles,
  Layers,
  ChevronRight,
  ChevronDown,
  Info,
  Eye,
  PanelLeftClose,
  PanelLeftOpen,
  FileCode2,
  Wand2,
  Search,
  Maximize2,
  Minimize2,
  BarChart3,
  Network
} from 'lucide-react';
import { toast } from 'sonner';
import ChartRenderer from '../components/ChartRenderer';
import MermaidChart from '../components/MermaidChart';
import TableDataInspector from '../components/TableDataInspector';

const QueryPage = () => {
  const { selectedConnectionId: selectedConn, setConnectionId: setSelectedConn } = useWorkspaceStore();
  const [naturalQuery, setNaturalQuery] = useState('');
  const [inspectingTable, setInspectingTable] = useState<string | null>(null);
  const [generatedSql, setGeneratedSql] = useState('');
  const [results, setResults] = useState<any>(null);
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [tableSearch, setTableSearch] = useState('');

  const [showSchema, setShowSchema] = useState(true);
  const [activeBottomTab, setActiveBottomTab] = useState<'results' | 'chart' | 'diagrams'>('results');
  const [diagramTab, setDiagramTab] = useState<'erd' | 'dfd' | 'flow'>('erd');
  const [isEditorExpanded, setIsEditorExpanded] = useState(false);
  const [chartRec, setChartRec] = useState<any>(null);
  const [expandedTables, setExpandedTables] = useState<string[]>([]);
  const [insights, setInsights] = useState<any>(null);
  const [isGeneratingInsights, setIsGeneratingInsights] = useState(false);
  const [confirmWriteModal, setConfirmWriteModal] = useState<{ show: boolean; sql: string } | null>(null);

  const queryClient = useQueryClient();

  // Fetch connections
  const { data: connections, isLoading } = useQuery({
    queryKey: ['connections'],
    queryFn: async () => {
      const res = await connectionsApi.getConnections();
      return res.data || [];
    }
  });

  // Fetch schema
  const { data: schema, isLoading: schemaLoading } = useSchemaExtract(selectedConn);

  // Fetch History
  const { data: history } = useQuery({
    queryKey: ['history', selectedConn],
    queryFn: async () => {
      const res = await queryApi.getHistory(selectedConn || undefined);
      return res.data || [];
    }
  });

  // 1. Generate SQL Mutation
  const generateMutation = useMutation({
    mutationFn: (data: any) => queryApi.generateQuery(data),
    onSuccess: (res) => {
      setGeneratedSql(res.data.sql);
      setChartRec(res.data.chart_recommendation);
      toast.success('SQL Generated by AI');
      res.data.warnings?.forEach((w: string) => toast.warning(w));
    },
    onError: (err: any) => toast.error(err.message || 'Failed to generate SQL')
  });

  // 2. Execute SQL Mutation
  const executeMutation = useMutation({
    mutationFn: (data: any) => queryApi.executeQuery(data),
    onSuccess: async (res) => {
      const data = res.data;
      if (data && data.requiresConfirmation) {
        setConfirmWriteModal({ show: true, sql: generatedSql });
        return;
      }
      setResults(data);
      setCurrentPage(1);
      setActiveBottomTab('results');
      toast.success(`Query executed: ${data.rowCount || 0} rows returned`);
      queryClient.invalidateQueries({ queryKey: ['history'] });

      // Automatically trigger insights if data returned
      if (data.rows && data.rows.length > 0) {
        setIsGeneratingInsights(true);
        try {
          const insRes = await queryApi.getInsights({
            query: naturalQuery,
            results: data.rows.slice(0, 50),
            connectionId: selectedConn!
          });
          setInsights(insRes.data);
        } catch (error) {
          console.error("Insights generation failed", error);
        } finally {
          setIsGeneratingInsights(false);
        }
      }
    },
    onError: (err: any) => toast.error(err.message || 'Query failed')
  });

  // 3. Optimize SQL Mutation
  const optimizeMutation = useMutation({
    mutationFn: (data: any) => queryApi.optimizeQuery(data),
    onSuccess: (res) => {
      setGeneratedSql(res.data.optimizedSql);
      toast.success('SQL Optimized by AI');
    },
    onError: (err: any) => toast.error(err.message || 'Optimization failed')
  });

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedConn) return toast.error('Select a data source first');
    if (!naturalQuery.trim()) return toast.error('Enter a query description');
    generateMutation.mutate({ naturalQuery, connectionId: selectedConn });
  };

  const handleExecute = () => {
    if (!selectedConn) return toast.error('Select a data source');
    if (!generatedSql.trim()) return toast.error('No SQL to execute');
    executeMutation.mutate({ sql: generatedSql, connectionId: selectedConn });
  };

  const handleOptimize = () => {
    if (!selectedConn) return toast.error('Select a data source');
    if (!generatedSql.trim()) return toast.error('No SQL to optimize');
    optimizeMutation.mutate({ sql: generatedSql, connectionId: selectedConn });
  };

  const totalRows = results?.rows?.length || 0;
  const totalPages = Math.ceil(totalRows / pageSize);
  const paginatedRows = results?.rows ? results.rows.slice((currentPage - 1) * pageSize, currentPage * pageSize) : [];

  const filteredTables = schema?.tables?.filter((t: any) =>
    t.table_name.toLowerCase().includes(tableSearch.toLowerCase())
  ) || [];

  return (
    <div className="h-full min-h-0 flex flex-col overflow-hidden bg-[#090C13] text-slate-100">
      
      {/* ── 1. UNIFIED TOP BAR ── */}
      <header className="flex-shrink-0 flex items-center justify-between gap-3 px-4 py-2.5 border-b border-white/5 bg-[#0B0E18]/80 backdrop-blur-md">
        {/* Left: Schema toggle + Brand Badge */}
        <div className="flex items-center gap-2.5 flex-shrink-0">
          <button
            onClick={() => setShowSchema(v => !v)}
            className="p-1.5 rounded-lg hover:bg-white/10 text-slate-400 hover:text-white transition-all"
            title={showSchema ? "Collapse Schema Explorer" : "Expand Schema Explorer"}
          >
            {showSchema ? <PanelLeftClose size={15} /> : <PanelLeftOpen size={15} />}
          </button>
          <div className="flex items-center gap-1.5">
            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            <span className="text-xs font-bold text-white tracking-wide">SQL Copilot Studio</span>
            <span className="text-[10px] uppercase font-mono px-1.5 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-bold">
              AI Powered
            </span>
          </div>
        </div>

        {/* Center: Quick Query History Prompt Pills */}
        {history && history.length > 0 && (
          <div className="hidden lg:flex items-center gap-1.5 overflow-hidden max-w-md">
            <span className="text-[10px] uppercase font-mono text-slate-500 font-bold flex-shrink-0">Recent:</span>
            {history.slice(0, 2).map((h: any, idx: number) => (
              <button
                key={idx}
                onClick={() => setGeneratedSql(h.query_text)}
                className="text-[11px] text-slate-400 hover:text-blue-300 bg-white/5 hover:bg-white/10 px-2 py-0.5 rounded-md truncate max-w-[180px] transition-all border border-white/5"
                title={h.query_text}
              >
                {h.query_text}
              </button>
            ))}
          </div>
        )}

        {/* Right: Data Source Selector */}
        <div className="flex items-center gap-2 flex-shrink-0">
          <div className="flex items-center gap-1.5 bg-white/5 border border-white/8 rounded-xl px-2.5 py-1">
            <Database size={12} className="text-blue-400 flex-shrink-0" />
            <select
              className="bg-transparent border-none focus:ring-0 text-xs font-semibold text-white cursor-pointer max-w-[160px]"
              value={selectedConn || ''}
              onChange={(e) => setSelectedConn(e.target.value)}
            >
              <option value="" className="bg-slate-900 text-slate-400">
                {isLoading ? 'Loading...' : 'Select Connection'}
              </option>
              {Array.isArray(connections) && connections.map((conn: any) => (
                <option key={conn.id} value={conn.id} className="bg-slate-900 text-white">
                  {conn.name} ({conn.database_name})
                </option>
              ))}
            </select>
          </div>
        </div>
      </header>

      {/* ── 2. MAIN 2-PANEL WORKSPACE ── */}
      <div className="flex-1 min-h-0 flex overflow-hidden">

        {/* ── LEFT PANEL: Schema & Entity Explorer ── */}
        {showSchema && (
          <aside className="w-64 flex-shrink-0 flex flex-col border-r border-white/5 bg-[#0B0E18]/60 overflow-hidden">
            {/* Header & Instant Search Filter */}
            <div className="p-2.5 border-b border-white/5 space-y-2 bg-white/2">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-1.5">
                  <Layers className="text-blue-400" size={13} />
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-300">Schema Explorer</span>
                </div>
                <span className="text-[10px] font-mono text-slate-500">{filteredTables.length} tables</span>
              </div>
              <div className="flex items-center gap-1.5 bg-[#121722] border border-white/10 rounded-lg px-2 py-1">
                <Search size={11} className="text-slate-500" />
                <input
                  type="text"
                  placeholder="Filter tables & views..."
                  value={tableSearch}
                  onChange={(e) => setTableSearch(e.target.value)}
                  className="bg-transparent text-[11px] text-white placeholder:text-slate-600 focus:outline-none w-full"
                />
              </div>
            </div>

            {/* Tree List */}
            <div className="flex-1 overflow-y-auto p-2 space-y-1 custom-scrollbar">
              {!selectedConn ? (
                <div className="h-full flex flex-col items-center justify-center text-center opacity-40 p-6 space-y-2">
                  <Info size={20} className="text-slate-500" />
                  <p className="text-xs font-medium">Select a connection to view tables</p>
                </div>
              ) : schemaLoading ? (
                <div className="flex flex-col items-center justify-center p-8 space-y-2 text-slate-500">
                  <Loader2 size={18} className="animate-spin text-blue-500" />
                  <span className="text-[10px] uppercase font-bold tracking-wider">Extracting Tables...</span>
                </div>
              ) : filteredTables.length === 0 ? (
                <p className="text-xs text-slate-600 text-center py-8 italic">No tables matched</p>
              ) : (
                filteredTables.map((table: any, idx: number) => {
                  const isExpanded = expandedTables.includes(table.table_name);
                  return (
                    <div key={`${table.table_name}-${idx}`} className="rounded-xl border border-white/5 bg-white/2 overflow-hidden transition-all">
                      <div className="flex items-center justify-between p-1.5 group/table hover:bg-white/5">
                        <button
                          onClick={() => setExpandedTables(prev =>
                            isExpanded ? prev.filter(t => t !== table.table_name) : [...prev, table.table_name]
                          )}
                          className="flex items-center space-x-1.5 text-slate-300 hover:text-white text-left transition-all truncate flex-1"
                        >
                          {isExpanded ? <ChevronDown size={12} className="text-blue-400" /> : <ChevronRight size={12} className="text-slate-500" />}
                          <TableIcon size={12} className="text-blue-400/70 flex-shrink-0" />
                          <span className="text-xs font-semibold truncate">{table.table_name}</span>
                        </button>
                        <button
                          onClick={() => setInspectingTable(table.table_name)}
                          className="opacity-0 group-hover/table:opacity-100 transition-all p-1 hover:bg-white/10 text-slate-400 hover:text-blue-400 rounded-md flex items-center justify-center flex-shrink-0"
                          title="Browse Table Records"
                        >
                          <Eye size={11} />
                        </button>
                      </div>

                      {isExpanded && (
                        <div className="px-3 pb-2 pt-1 space-y-1.5 border-t border-white/5 bg-black/20 text-[11px]">
                          <span className="text-[9px] font-bold text-slate-500 uppercase tracking-widest block">Columns</span>
                          {table.columns.map((col: any, cIdx: number) => (
                            <div
                              key={`${table.table_name}-${col.column_name}-${cIdx}`}
                              onClick={() => setNaturalQuery(prev => prev ? `${prev} ${col.column_name}` : col.column_name)}
                              className="flex items-center justify-between text-slate-400 py-0.5 cursor-pointer hover:text-blue-300"
                              title="Click to insert into prompt"
                            >
                              <span className="truncate">{col.column_name}</span>
                              <span className="text-[9px] uppercase opacity-60 bg-white/5 px-1 rounded font-mono">{col.data_type}</span>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })
              )}
            </div>
          </aside>
        )}

        {/* ── RIGHT CANVAS: Pro-Studio Vertical Workspace ── */}
        <div className="flex-1 min-w-0 flex flex-col min-h-0 overflow-hidden bg-[#0A0D14]">

          {/* 1. Hero Natural Language Prompt Section */}
          <div className="p-3 border-b border-white/5 bg-[#0B0E18]/60 flex-shrink-0">
            <form onSubmit={handleGenerate} className="max-w-4xl mx-auto">
              <div className="flex items-center gap-2 bg-[#121722] border border-white/10 focus-within:border-blue-500/60 focus-within:ring-1 focus-within:ring-blue-500/30 rounded-2xl px-3.5 py-2 shadow-xl transition-all">
                <div className="flex items-center gap-1.5 text-blue-400 flex-shrink-0">
                  <Wand2 size={15} />
                  <span className="text-xs font-bold uppercase tracking-wider hidden sm:inline">Ask AI:</span>
                </div>
                <input
                  type="text"
                  className="flex-1 bg-transparent text-[13.5px] text-white placeholder:text-slate-500 focus:outline-none leading-normal"
                  placeholder="e.g. 'Show revenue per user for the last 30 days grouped by country and order count'..."
                  value={naturalQuery}
                  onChange={(e) => setNaturalQuery(e.target.value)}
                />
                <button
                  type="submit"
                  disabled={generateMutation.isPending || !naturalQuery.trim()}
                  className="bg-blue-600 hover:bg-blue-500 disabled:opacity-40 text-white px-3.5 py-1.5 rounded-xl transition-all shadow-md shadow-blue-600/25 flex items-center gap-1.5 text-xs font-bold active:scale-95 flex-shrink-0"
                >
                  {generateMutation.isPending ? <Loader2 size={13} className="animate-spin" /> : <ArrowRight size={13} />}
                  <span>Generate SQL</span>
                </button>
              </div>
            </form>
          </div>

          {/* 2. Monaco SQL Code Editor (Resizable / Expandable) */}
          <div className={`flex flex-col border-b border-white/5 transition-all duration-200 ${isEditorExpanded ? 'flex-1' : results ? 'h-[42%]' : 'flex-1'}`}>
            <div className="flex items-center justify-between px-4 py-2 border-b border-white/5 bg-[#0B0E18]/40 flex-shrink-0">
              <div className="flex items-center space-x-2">
                <FileCode2 className="text-blue-400" size={14} />
                <span className="text-xs font-bold tracking-wide text-slate-300">Monaco SQL Studio</span>
                {generatedSql && <span className="text-[10px] font-mono text-slate-500 px-1.5 py-0.5 rounded bg-white/5">Compiled</span>}
              </div>
              <div className="flex items-center space-x-2">
                <button
                  onClick={handleOptimize}
                  disabled={optimizeMutation.isPending || !generatedSql}
                  className="bg-blue-500/10 hover:bg-blue-500/20 disabled:opacity-30 text-blue-400 px-3 py-1 rounded-lg text-xs font-semibold flex items-center space-x-1.5 transition-all border border-blue-500/20 active:scale-95"
                >
                  {optimizeMutation.isPending ? <Loader2 size={12} className="animate-spin" /> : <Sparkles size={12} />}
                  <span>Optimize</span>
                </button>
                <button
                  onClick={handleExecute}
                  disabled={executeMutation.isPending || !generatedSql}
                  className="bg-emerald-600 hover:bg-emerald-500 disabled:opacity-30 text-white px-3.5 py-1 rounded-lg text-xs font-bold flex items-center space-x-1.5 transition-all shadow-md shadow-emerald-600/25 active:scale-95"
                >
                  {executeMutation.isPending ? <Loader2 size={12} className="animate-spin" /> : <Play size={12} fill="currentColor" />}
                  <span>Execute SQL</span>
                </button>
                <button
                  onClick={() => setIsEditorExpanded(v => !v)}
                  className="p-1 text-slate-400 hover:text-white rounded-lg hover:bg-white/5 transition-all"
                  title={isEditorExpanded ? "Restore Split View" : "Maximize Editor"}
                >
                  {isEditorExpanded ? <Minimize2 size={13} /> : <Maximize2 size={13} />}
                </button>
              </div>
            </div>

            <div className="flex-1 min-h-0">
              <Editor
                height="100%"
                defaultLanguage="sql"
                theme="vs-dark"
                value={generatedSql}
                onChange={(val) => setGeneratedSql(val || '')}
                options={{
                  minimap: { enabled: false },
                  fontSize: 13,
                  padding: { top: 12 },
                  automaticLayout: true,
                  scrollBeyondLastLine: false
                }}
              />
            </div>
          </div>

          {/* 3. Bottom Output Pane (Tabs: Table Data | AI Visuals | Schema Flow) */}
          {!isEditorExpanded && (
            <div className="flex-1 min-h-0 flex flex-col bg-[#0D111A] overflow-hidden">
              
              {/* Output Tab Switcher */}
              <div className="px-4 py-2 border-b border-white/5 flex items-center justify-between bg-white/2 flex-shrink-0">
                <div className="flex items-center gap-1 bg-white/5 border border-white/8 p-0.5 rounded-xl">
                  <button
                    onClick={() => setActiveBottomTab('results')}
                    className={`flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-bold transition-all ${
                      activeBottomTab === 'results' ? 'bg-purple-600 text-white shadow-md shadow-purple-600/30' : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    <TableIcon size={12} />
                    <span>Data Grid ({totalRows})</span>
                  </button>
                  <button
                    onClick={() => setActiveBottomTab('chart')}
                    disabled={(!chartRec || chartRec.type === 'none') && !insights}
                    className={`flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-bold transition-all ${
                      activeBottomTab === 'chart' ? 'bg-purple-600 text-white shadow-md shadow-purple-600/30' : 'text-slate-400 hover:text-white disabled:opacity-25'
                    }`}
                  >
                    <BarChart3 size={12} />
                    <span>AI Visuals & Story</span>
                  </button>
                  <button
                    onClick={() => setActiveBottomTab('diagrams')}
                    disabled={!insights?.erd_mermaid && !insights?.dfd_mermaid && !insights?.flow_mermaid && !schema?.erd_mermaid}
                    className={`flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-bold transition-all ${
                      activeBottomTab === 'diagrams' ? 'bg-purple-600 text-white shadow-md shadow-purple-600/30' : 'text-slate-400 hover:text-white disabled:opacity-25'
                    }`}
                  >
                    <Network size={12} />
                    <span>System Flow</span>
                  </button>
                </div>

                {isGeneratingInsights && (
                  <div className="flex items-center gap-2 text-xs text-slate-400 font-medium animate-pulse">
                    <Loader2 size={12} className="animate-spin text-blue-400" />
                    <span>Analyzing data patterns...</span>
                  </div>
                )}
              </div>

              {/* Tab 1: Full-Width Data Table Grid */}
              {activeBottomTab === 'results' && (
                <div className="flex-1 flex flex-col min-h-0 justify-between">
                  <div className="flex-1 overflow-auto custom-scrollbar">
                    {results && results.fields && results.fields.length > 0 ? (
                      <table className="w-full text-left text-xs">
                        <thead className="bg-[#111622] sticky top-0 z-10">
                          <tr>
                            {results.fields.map((f: any) => (
                              <th key={f.name} className="px-4 py-2.5 border-b border-white/10 font-bold text-slate-300 uppercase tracking-wider text-[11px]">{f.name}</th>
                            ))}
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-white/5 font-mono text-[12px]">
                          {paginatedRows.map((row: any, i: number) => (
                            <tr key={i} className="hover:bg-white/5 transition-colors">
                              {results.fields.map((f: any) => (
                                <td key={f.name} className="px-4 py-2 text-slate-300 truncate max-w-[240px]">{row[f.name]?.toString() || 'null'}</td>
                              ))}
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    ) : !results ? (
                      <div className="h-full flex flex-col items-center justify-center opacity-30 text-center py-12 space-y-2">
                        <TableIcon size={28} />
                        <p className="text-xs font-semibold">Run a query to inspect live table records</p>
                      </div>
                    ) : (
                      <div className="h-full flex flex-col items-center justify-center opacity-40 text-center py-12 px-6 space-y-2">
                        <CheckCircle2 size={28} className="text-emerald-500" />
                        <p className="text-xs font-bold">{results?.message || 'Query executed successfully with 0 records'}</p>
                      </div>
                    )}
                  </div>

                  {/* Pagination Bar */}
                  {totalRows > 0 && (
                    <div className="flex items-center justify-between px-4 py-2 border-t border-white/5 bg-[#0B0E18]/90 text-xs select-none flex-shrink-0">
                      <div className="flex items-center space-x-2 text-slate-400">
                        <span>Show</span>
                        <select
                          value={pageSize}
                          onChange={(e) => { setPageSize(Number(e.target.value)); setCurrentPage(1); }}
                          className="bg-white/5 border border-white/10 rounded-lg px-2 py-0.5 text-white font-bold cursor-pointer focus:outline-none text-xs"
                        >
                          {[5, 10, 20, 50, 100].map(sz => (
                            <option key={sz} value={sz} className="bg-slate-900">{sz}</option>
                          ))}
                        </select>
                        <span>of {totalRows} records</span>
                      </div>

                      <div className="flex items-center space-x-1.5">
                        <button
                          onClick={() => setCurrentPage(1)}
                          disabled={currentPage === 1}
                          className="px-2.5 py-1 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:text-white disabled:opacity-30 disabled:pointer-events-none transition-all text-xs font-bold"
                        >
                          First
                        </button>
                        <button
                          onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                          disabled={currentPage === 1}
                          className="px-2.5 py-1 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:text-white disabled:opacity-30 disabled:pointer-events-none transition-all text-xs font-bold"
                        >
                          Prev
                        </button>
                        <span className="px-2 text-slate-400 text-xs font-medium">
                          Page <strong className="text-white">{currentPage}</strong> / <strong className="text-white">{totalPages || 1}</strong>
                        </span>
                        <button
                          onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                          disabled={currentPage === totalPages || totalPages === 0}
                          className="px-2.5 py-1 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:text-white disabled:opacity-30 disabled:pointer-events-none transition-all text-xs font-bold"
                        >
                          Next
                        </button>
                        <button
                          onClick={() => setCurrentPage(totalPages)}
                          disabled={currentPage === totalPages || totalPages === 0}
                          className="px-2.5 py-1 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:text-white disabled:opacity-30 disabled:pointer-events-none transition-all text-xs font-bold"
                        >
                          Last
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* Tab 2: AI Chart Visuals & Story */}
              {activeBottomTab === 'chart' && (
                <div className="p-6 space-y-6 overflow-y-auto custom-scrollbar h-full">
                  {chartRec && chartRec.type !== 'none' && results?.rows && (
                    <div className="space-y-3">
                      <div className="flex items-center justify-between">
                        <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider">{chartRec?.label || 'AI Recommended Chart'}</h4>
                        <span className="text-[10px] bg-blue-500/10 text-blue-400 px-2 py-0.5 rounded border border-blue-500/20 uppercase font-bold">{chartRec?.type}</span>
                      </div>
                      <div className="h-[240px] bg-black/30 p-4 rounded-2xl border border-white/5">
                        <ChartRenderer
                          type={chartRec.type}
                          data={results?.rows || []}
                          xAxis={chartRec.x_axis}
                          yAxis={chartRec.y_axis}
                          label={chartRec.label}
                        />
                      </div>
                    </div>
                  )}

                  {insights && (
                    <div className="space-y-3">
                      <div className="flex items-center space-x-2">
                        <Sparkles size={14} className="text-purple-400" />
                        <h5 className="text-xs font-bold uppercase tracking-wider text-slate-300">AI Data Story & Insights</h5>
                      </div>
                      <div className="bg-[#121722] rounded-2xl p-4 border border-white/10 space-y-3">
                        <p className="text-xs text-slate-200 leading-relaxed font-medium">
                          {insights.summary}
                        </p>
                        {insights.key_findings && (
                          <div className="space-y-1.5 pt-2 border-t border-white/5">
                            <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider">Key Findings</span>
                            <ul className="space-y-1">
                              {insights.key_findings.map((f: string, i: number) => (
                                <li key={i} className="flex items-start space-x-2 text-[11px] text-slate-400">
                                  <CheckCircle2 size={12} className="mt-0.5 text-emerald-500/60 flex-shrink-0" />
                                  <span>{f}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* Tab 3: System Flow Diagrams */}
              {activeBottomTab === 'diagrams' && (
                <div className="h-full flex flex-col min-h-0 overflow-hidden">
                  <div className="flex items-center space-x-4 px-4 py-2 border-b border-white/5 bg-white/2 flex-shrink-0">
                    {(['erd', 'dfd', 'flow'] as const).map(t => (
                      <button
                        key={t}
                        onClick={() => setDiagramTab(t)}
                        className={`text-xs font-semibold pb-1 border-b-2 transition-all ${diagramTab === t ? 'text-blue-400 border-blue-400 font-bold' : 'text-slate-500 border-transparent hover:text-slate-300'}`}
                      >
                        {t === 'erd' ? 'Schema ERD' : t === 'dfd' ? 'Data Flow (DFD)' : 'Operational Sequence'}
                      </button>
                    ))}
                  </div>

                  <div className="flex-1 overflow-auto p-6 custom-scrollbar">
                    {diagramTab === 'erd' && (
                      <div className="bg-slate-900/40 rounded-2xl p-6 border border-white/5 shadow-2xl">
                        <MermaidChart chart={insights?.erd_mermaid || schema?.erd_mermaid || ''} />
                      </div>
                    )}
                    {diagramTab === 'dfd' && (
                      <div className="bg-slate-900/40 rounded-2xl p-6 border border-white/5 shadow-2xl">
                        <MermaidChart chart={insights?.dfd_mermaid || schema?.dfd_mermaid || ''} />
                      </div>
                    )}
                    {diagramTab === 'flow' && (
                      <div className="bg-slate-900/40 rounded-2xl p-6 border border-white/5 shadow-2xl">
                        <MermaidChart chart={insights?.flow_mermaid || ''} />
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Table Data Inspector Modal */}
      {inspectingTable && selectedConn && (
        <TableDataInspector
          connectionId={selectedConn}
          tableName={inspectingTable}
          onClose={() => setInspectingTable(null)}
        />
      )}

      {/* Confirm Write Query Modal */}
      {confirmWriteModal?.show && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/70 backdrop-blur-md animate-in fade-in duration-200">
          <div className="w-full max-w-md bg-[#0F1420] border border-white/10 p-8 rounded-3xl shadow-2xl space-y-5 animate-in zoom-in-95 duration-200">
            <div className="w-12 h-12 rounded-2xl bg-amber-500/10 text-amber-500 flex items-center justify-center animate-pulse">
              <ShieldAlert size={24} />
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold text-white tracking-wide">Confirm Write Query</h3>
              <p className="text-slate-400 text-xs leading-relaxed">
                This query will execute mutation statements (INSERT, UPDATE, DELETE, ALTER).
              </p>
            </div>
            <div className="flex flex-col gap-2 pt-2">
              <button
                onClick={() => {
                  const sql = confirmWriteModal.sql;
                  setConfirmWriteModal(null);
                  executeMutation.mutate({ sql, connectionId: selectedConn, confirmWrite: true });
                }}
                className="w-full py-3 bg-amber-600 hover:bg-amber-500 text-white rounded-2xl font-bold text-xs shadow-lg shadow-amber-600/20 transition-all uppercase tracking-wider"
              >
                Confirm and Execute
              </button>
              <button
                onClick={() => setConfirmWriteModal(null)}
                className="w-full py-3 bg-white/5 text-slate-400 hover:text-white rounded-2xl font-bold text-xs transition-all"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default QueryPage;
