import { Link } from 'react-router-dom';
import { FileCheck, ArrowLeft, ShieldAlert } from 'lucide-react';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-[#020617] text-white p-6 sm:p-12 flex justify-center selection:bg-purple-500/30">
      <div className="max-w-4xl w-full space-y-8 animate-in fade-in duration-300">
        <Link to="/" className="inline-flex items-center space-x-2 text-sm text-slate-400 hover:text-white transition-colors">
          <ArrowLeft size={16} />
          <span>Back to Home</span>
        </Link>

        <div className="flex items-center space-x-3">
          <div className="p-3 bg-purple-500/10 text-purple-400 rounded-2xl">
            <FileCheck size={28} />
          </div>
          <div>
            <h1 className="text-3xl font-extrabold tracking-tight">Global Terms of Service & Enterprise Agreement</h1>
            <p className="text-xs text-slate-400 mt-1">Effective Date: August 2026 | Universal Limitation of Liability & Indemnification</p>
          </div>
        </div>

        <div className="glass p-8 md:p-10 rounded-[2rem] border border-white/5 space-y-8 text-sm text-slate-300 leading-relaxed">
          
          {/* Important Disclaimers Callout */}
          <div className="p-5 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-start gap-3 text-purple-200 text-xs">
            <ShieldAlert size={20} className="shrink-0 text-purple-400 mt-0.5" />
            <p>
              By accessing, creating an account, or connecting any database to Atlas AI, you explicitly agree that Atlas AI is an autonomous advisory tool. You maintain sole operational responsibility for verifying and executing all schema migrations, DDL statements, and SQL queries in your environments.
            </p>
          </div>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-white uppercase tracking-wider">1. User Affirmation & Mandatory Consent</h2>
            <p>
              By creating an account, registering an organization, or checking the terms consent box, you warrant that you are authorized to bind yourself or your company to this Agreement. If you do not agree to all terms, you are strictly prohibited from using the platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-white uppercase tracking-wider">2. Universal Limitation of Liability (Platform & Owner Shield)</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE GLOBAL LAW, IN NO EVENT SHALL ATLAS AI, ITS FOUNDERS, DIRECTORS, DEVELOPERS, AFFILIATES, OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, DATA LOSS, CORRUPTION OF DATABASE TABLES, SERVER DOWNTIME, FINANCIAL PENALTIES, OR BUSINESS INTERRUPTION ARISING OUT OF THE USE OF, OR INABILITY TO USE, THIS SERVICE.
            </p>
            <p className="text-xs text-slate-400">
              Atlas AI provides AI-assisted database recommendations, 3NF blueprints, and SQL queries "AS IS" and "AS AVAILABLE" without warranties of any kind, whether express or implied.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-white uppercase tracking-wider">3. Full Customer Indemnification</h2>
            <p>
              You agree to defend, indemnify, and hold harmless Atlas AI, its platform creators, and hosting infrastructure providers from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including attorney's fees) arising from:
            </p>
            <ul className="list-disc pl-5 space-y-1.5 text-xs text-slate-400">
              <li>Your execution of any generated SQL, DDL, or database migration scripts on live infrastructure.</li>
              <li>Any security breach, data exposure, or unauthorized access occurring within your own cloud databases.</li>
              <li>Your violation of any third-party right, privacy regulation, or intellectual property laws.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-white uppercase tracking-wider">4. 100% Customer Intellectual Property Ownership</h2>
            <p>
              You retain absolute, unconditional ownership of all database designs, schemas, queries, and business requirements submitted to or generated by Atlas AI. Atlas AI does NOT train public AI foundation models on your private schema structures.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-white uppercase tracking-wider">5. Subscription Billing, Trials & Cancellation</h2>
            <p>
              Accounts start with a <strong>7-Day Free Enterprise Trial</strong>. Paid subscription plans (Individual, Growth Team, Mega Enterprise) are billed on a recurring monthly or annual basis via Razorpay or Stripe. You may cancel at any time via your self-serve Billing Dashboard before renewal.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-white uppercase tracking-wider">6. Governing Law & Dispute Resolution</h2>
            <p>
              This Agreement shall be governed by and construed in accordance with the laws of Delaware / International Commercial Arbitration frameworks, without giving effect to any principles of conflicts of law.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
